### ISSUE TITLE
Missing references

### ISSUE THREAD

**Issue by vangras** [rebeccaXam/XamForms.Controls.Calendar#1]
Hi,

I installed the component (v.1.0.3) with NuGet from Visual Studio 2015 Update 3, adding it to all projects in a Xamarin Forms (v.2.3.0.107) solution, but there are some issues:

- when running on Windows 10 either the UWP or Win8.1 projects, I get the following error: WinRT information: Cannot locate resource from ‘ms-appx:///XamForms.Controls.Calendar.UWP/Resources.xaml’.

- the XamForms.Controls.Calendar.iOS isn't added to the iOS project. I had to add it manually to the references. I don't have a MAC at hand at the moment, so not sure if it's due to that.

I downloaded the code, updated to Xamarin Forms 2.3.0.107, and ran the sample and it works fine on Windows 10. Droid version also runs fine on Android device.

P.S. Also a note on the XAML sample in readme: shouldn't it say "<controls:**Calendar** Padding=..." instead of "<controls:**CalendarControl** Padding=" ?

**Comment by rebeccaXam** [comment]
Thanks for reporting the issues. I will try to fix this asap.

P.S. Indeed you are right ;) Thanks

**Comment by rebeccaXam** [comment]
It should be fixed now in version v.1.0.4

**Comment by vangras** [comment]
Perfect, thanks!
