### ISSUE TITLE
When Changing Months, the days do not update properly

### ISSUE THREAD

**Issue by KRA2008** [rebeccaXam/XamForms.Controls.Calendar#10]
I'm seeing the same behavior described in #2 but on iOS (that issue was concentrated on UWP). This module is awesome on Android.

**Comment by KRA2008** [comment]
@rebeccaXam it looks like the analagous fix for #2 can be applied to iOS to fix things. This is a relief because I love this module. I'm digging in to see if I can find the cause.

**Comment by KRA2008** [comment]
Just as a note, when I did look into this I couldn't figure it out. I can't promise I'll ever be able to find an answer.

**Comment by BlackPinpin** [comment]
Hello, I have the same problem and I can't find how to resolve it. If someone have a solution it would be a pleasure to read it, because a calendar who don't display correct dates is not very useful... :(

**Comment by BlackPinpin** [comment]
Ho, in fact it works on iOS, it was just because I thought that the nugget was installed in the iOS project but it was just installed in the PCL

**Comment by Teviko** [comment]
In 1.0.7, this issue still exists on iOS release build. When changing month, the days do not update properly. But it is fine in iOS debug build. 
Although I can still enable debugging option in the iOS release build, to deploy a larger app and dismiss this issue.
Hope someone has a solution to fix this issue.

**Comment by Teviko** [comment]
Try add: [assembly: ExportRenderer(typeof(XamForms.Controls.CalendarButton), typeof(XamForms.Controls.iOS.CalendarButtonRenderer))] 
It works fine for me now in iOS release build.

**Comment by johankson** [comment]
This should be in the documentation in the readme.md. It cost me several hours before I found this. Yes I know I should always read though the issues, but this seems like something that has to be added. :)

Otherwise, great control!

**Comment by rebeccaXam** [comment]
I added a ``Important`` note on the Readme and a Troubleshoot for this, hoop this helps ;)

**Comment by akhilgeorge303** [comment]
> Try add: [assembly: ExportRenderer(typeof(XamForms.Controls.CalendarButton), typeof(XamForms.Controls.iOS.CalendarButtonRenderer))]
> It works fine for me now in iOS release build.

where to add?assembly info?
