### ISSUE TITLE
WhenChanging Month App Crashing  

### ISSUE THREAD

**Issue by akhilgeorge303** [rebeccaXam/XamForms.Controls.Calendar#109]
Unhandled Exception:

System.NullReferenceException: <Timeout exceeded getting exception details>

error info

**Comment by lubiepomaranczki** [comment]
Are you using Forms 4.0 or higher?

**Comment by akhilgeorge303** [comment]
Yes. 4.1.0

**Comment by akhilgeorge303** [comment]
the crash  is only in ios ,in android its fine

**Comment by lubiepomaranczki** [comment]
Indeed. Try installing [XamForms.Enhanced.Calendar](https://www.nuget.org/packages/XamForms.Enhanced.Calendar/) which is a fork of this repository but updated. If it doesn't work, please raise an issue [here](https://github.com/lubiepomaranczki/XamForms.Controls.Calendar/issues)

Good luck! 🚀

**Comment by akhilgeorge303** [comment]
Thanks @lubiepomaranczki i will check it.

**Comment by akhilgeorge303** [comment]
its working fine now.
