### ISSUE TITLE
new Feature show number of week

### ISSUE THREAD

**Issue by PlusInf0Iulia** [rebeccaXam/XamForms.Controls.Calendar#12]
Hi i've added your calendar to my app and i love it!!! will you improve it with the number of the week? i need this functionality . thank you very much

**Comment by rebeccaXam** [comment]
I will add an option for this in the next version 1.0.6:
<img width="400" alt="screen shot 2016-12-06 at 15 00 17" src="https://cloud.githubusercontent.com/assets/19565685/20928155/bffc3b22-bbc4-11e6-8572-a4d17cc4b9e2.png">

**Comment by rebeccaXam** [comment]
I release version 1.0.6. 
Use `ShowNumberOfWeek` to show the numbers of the week in front.
