### ISSUE TITLE
Disable selection, other than SpecialDates

### ISSUE THREAD

**Issue by Dids** [rebeccaXam/XamForms.Controls.Calendar#13]
Not sure if this component supports this or not, but in my particular case, I'd need something like this.

Essentially, just disable selection by default, then enable manually for each SpecialDate.

EDIT: I tried setting SelectedDate to DateTime.MinValue, in hopes of quickly deselecting dates that aren't allowed, but I guess it doesn't support two way binding, or something else is blocking it.

**Comment by rebeccaXam** [comment]
I will include a `DisableAllDates` option to disable all dates by default, you can then enable them again by setting SpecialDates, in the next version 1.0.6

**Comment by Dids** [comment]
That would be great, thank you! :)

**Comment by rebeccaXam** [comment]
Version 1.0.6 is available now.

**Comment by Dids** [comment]
Just tested it and it works like a charm, thank you!
