### ISSUE TITLE
feature request: bindable property to set whether day labels are bold

### ISSUE THREAD

**Issue by KRA2008** [rebeccaXam/XamForms.Controls.Calendar#17]

**Comment by KRA2008** [comment]
I think I can do a pull request for this one.

**Comment by rebeccaXam** [comment]
I notices that `WeekdaysFontAttributes` was indeed missing when going through the code.
I will release a new version 1.0.6 today (it will be included)

**Comment by rebeccaXam** [comment]
This should be available now in version 1.0.6
