### ISSUE TITLE
feature request: bindable property to choose whether month label is bold

### ISSUE THREAD

**Issue by KRA2008** [rebeccaXam/XamForms.Controls.Calendar#18]
I know it's possible to totally wipe out the MonthNavigationLayout but all I want to do is turn off the bolding of the month, so it seems like overkill to do that.

**Comment by KRA2008** [comment]
I think I can do a pull request for this one.

**Comment by rebeccaXam** [comment]
Actually this is already possible:
```
calendar.TitleLabel.FontAttributes = FontAttributes.Bold;
```
But feel free to write direct BindableProperties for this :)

PS: I am very, very happy for your help, but please wait until this weekend, before doing pull request.
I have restructured the whole code for more readability and overview and it would be really hard to merge. All header logic can now be found in Calendar.MonthNavigation.cs

**Comment by rebeccaXam** [comment]
Fix in bindable property ``TitleLabelFontAttributes`` in 1.0.8
