### ISSUE TITLE
feature request: make the color of the month arrows a bindable property

### ISSUE THREAD

**Issue by KRA2008** [rebeccaXam/XamForms.Controls.Calendar#19]
Again, wiping out the whole month navigation seems like overkill for this.

I think I can do this with a pull request.

**Comment by rebeccaXam** [comment]
Actually this is already possible: 
```
calendar.TitleLeftArrow.TextColor = Color.Blue;
calendar.TitleRightArrow.TextColor = Color.Blue;
```
But feel free to write direct BindableProperties for this :)

PS: I am very, very happy for your help, but please wait until this weekend, before doing pull request.
I have restructured the whole code for more readability and overview and it would be really hard to merge. All header logic can now be found in `Calendar.MonthNavigation.cs`

**Comment by rebeccaXam** [comment]
Fix in bindable property ``TitleLeftArrowTextColor`` and ``TitleRightArrowTextColor``  in 1.0.8
