### ISSUE TITLE
When Changing Months, the days do not update properly

### ISSUE THREAD

**Issue by zawadzkip** [rebeccaXam/XamForms.Controls.Calendar#2]
![image](https://cloud.githubusercontent.com/assets/7703723/16826681/d5f50f8c-4944-11e6-9d47-d89eac762a01.png)
(Start Month)
![image](https://cloud.githubusercontent.com/assets/7703723/16826628/7598c6f6-4944-11e6-9064-94ecb38b856e.png)
(End Month)

When I navigate from month to month, the days do not update properly. For example, I started in August of 2016, and the Dates/Days are correct. However, when I use the navigation arrow to go to the month of July, the days are not correct. July 13th for example, should be on a Wednesday but it is not.

**Comment by rebeccaXam** [comment]
Thanks for reporting the issue. I can reproduce this problem in Windows UWP in release mode. Did you see this problem on any other platform?

I looked into it and somehow the ExportRenderer is not working.
Try adding this to your UWP projects AssemblyInfo.cs file:

```
[assembly:Xamarin.Forms.Platform.UWP.ExportRenderer(typeof(XamForms.Controls.CalendarButton), typeof(XamForms.Controls.Windows.CalendarButtonRenderer))]
```

**Comment by zawadzkip** [comment]
@rebeccaXam I emailed you back before reading the assembly code. What will I have to do to make this work for iOS and Android? I'm guessing...
```
[assembly:Xamarin.Forms.Platform.iOS.ExportRenderer(typeof(XamForms.Controls.CalendarButton), typeof(XamForms.Controls.iOS.CalendarButtonRenderer))]

[assembly:Xamarin.Forms.Platform.Android.ExportRenderer(typeof(XamForms.Controls.CalendarButton), typeof(XamForms.Controls.Android.CalendarButtonRenderer))]

```

**Comment by zawadzkip** [comment]
After re-testing, the issue does not exist on android but does exist on iOS.

**Comment by zawadzkip** [comment]
@rebeccaXam Just wanted to confirm that the issue still exists on iOS, even after updating to 1.0.4

**Comment by Teviko** [comment]
In 1.0.7, this issue still exists on iOS release build. When changing month, the days do not update properly. But it is fine in iOS debug build. 
Although I can still enable debugging option in the iOS release build, to deploy a larger app and dismiss this issue.
Hope someone has a solution to fix this issue.

**Comment by Teviko** [comment]
https://github.com/rebeccaXam/XamForms.Controls.Calendar/issues/10

**Comment by snem1216** [comment]
The fix for this shown in the README did not work for me, I had to do this instead:
`[assembly: Xamarin.Forms.ExportRenderer(typeof(XamForms.Controls.CalendarButton), typeof(XamForms.Controls.<Platform>.CalendarButtonRenderer))]`
However, I only experienced this issue on iOS.

**Comment by snem1216** [comment]
The fix that was shown in the README did not work for me, I had to do this instead in the platform project's AssemblyInfo.cs:
`[assembly: Xamarin.Forms.ExportRenderer(typeof(XamForms.Controls.CalendarButton), typeof(XamForms.Controls.<Platform>.CalendarButtonRenderer))]`
ExportRenderer is no longer in the platform-specific namespaces it seems.
