### ISSUE TITLE
Calendar Button Template Not updating.

### ISSUE THREAD

**Issue by srinig29** [rebeccaXam/XamForms.Controls.Calendar#23]
Hi,

I'm trying to update the CalendarButton template on an action, visually it is not getting updated unless the user click that button. 
Is there any visual update method which I can call to update the template of calendar button on an action?

**Comment by rebeccaXam** [comment]
Sorry for the late response, I was quit busy the last 2 months.
This is probably related to 'Possible bug: Selected Date #20' and will be fixed in 1.0.8

**Comment by rebeccaXam** [comment]
Should be fixed in 1.0.8 if all else fails use ``calendar.ForceRedraw()`` this triggers a full redraw of the calendar.
If the problem persists please reopen this issue.
