### ISSUE TITLE
Is there a way to select only one date in a whole calendar control which has multiple months added in a year.

### ISSUE THREAD

**Issue by pradeeparutla** [rebeccaXam/XamForms.Controls.Calendar#25]
Current functionality:
1. If I have added 5 months in a calendar, I can select 5 different dates at one point of time(One date in each month). Date selection is provided month wise. 

Do we have any option, so that if one date is selected in a calendar control(all other selected dates in other months also get deselected)

Requirement: Only one date should be selected in whole calendar control irrespective of date selected in different months.

**Comment by pradeeparutla** [comment]
![calendar_datesselected_differentmonths](https://cloud.githubusercontent.com/assets/21239399/22422085/9e028662-e710-11e6-87da-d92d12e63166.jpg)

I want only one date to be selected at a time. As in the image attached. total of two dates are selected in the calendar control.

**Comment by rebeccaXam** [comment]
Hallo, I do not understand how you added 5 months to the Calendar Control. To me it looks more like you added 5 Calendar controls after each other and you want one Date selected in all of these controls, am I correct?

When you used 5 Calendar Controls you could use:
```
public class CalendarVM : INotifyPropertyChanged
{
	public event PropertyChangedEventHandler PropertyChanged;
	private DateTime? _date;
	public DateTime? Date
	{
		get { return _date; }
		set
		{
			_date = value;
			PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Date));
		}
	}
}
```
And bind all the Calendar controls to the same BindingContext ``CalendarVM``.
```
var vm = new CalendarVM();
calendar1.SetBinding(Calendar.SelectedDateProperty, nameof(vm.Date));
calendar1.BindingContext = vm;
calendar2.SetBinding(Calendar.SelectedDateProperty, nameof(vm.Date));
calendar2.BindingContext = vm;
etc...........
```
or in xaml
```
<controls:Calendar SelectedDate="{Binding Date}" />
<controls:Calendar SelectedDate="{Binding Date}" />
<controls:Calendar SelectedDate="{Binding Date}" />
```
Then the selected date in all controls will be the same.
Hoop this helps ;)

**Comment by pradeeparutla** [comment]
Thankyou for the fast response. 

To answer your question: I have added 5 different calendar controls one after each other to display more than one month at a time and Is there any other way I can add more than one month and scroll through the months using vertical scroll, same as the built in calendar control for iOS?

I hope I am missing something here.

If I am using the 5 different calendar controls for displaying 5 different months, then is there any way that, If I select a date in February then the date should be highlighted with some color, then the previously selected month in january to be unselected and color should be as normal date?

**Comment by pradeeparutla** [comment]
Hi RebeccaXam,

Thankyou for the fast response and a great control.

If I am using the 5 different calendar controls for displaying 5 different months, then my issue is now resolved using the solution provided by you.

Is there any other way by using only one calendar control, I can add more than one month and scroll through the months using vertical scroll, same as the built in calendar control for iOS devices?

**Comment by evandroabukamel** [comment]
I have interest in this too. I tried to attach gestures to the calendar but no success.

**Comment by rebeccaXam** [comment]
To show multiple months to scroll through use ``ShowNumOfMonths`` = (1-12) in version 1.0.8
I added this as a feature in 1.0.8, please reopen this issue, if it is not fully fulfilled or open a new issue.

**Comment by pradeeparutla** [comment]
Thank you rebacca for the solution. When I am using 5 different calendar controls to display more than once calendar month, I have implemented your suggestion using the calendar view model to select only one date at a time in all the calendar controls. I am facing one new issue in android devices. Sometimes Date Clicked event is hitting twice on selecting a particular date other than the current month. Example: if current date selected in calendar is Jan 15th 2017, on selecting a date Feb 3rd 2017, Date clicked event is triggered twice(Event is triggering 2 times).

**Comment by VishVenu** [comment]
Hi,
I want to display one month dates at a time. Kindly help. 

Eg: Currently it is showing Jan 1 to 31 and Feb 1 to to 11. I want to display only Jan 1 to 31 at a time.
