### ISSUE TITLE
Run at iPhone Simulator is Crash

### ISSUE THREAD

**Issue by prupleCode** [rebeccaXam/XamForms.Controls.Calendar#28]
Error is The Type initializer for "XamForms.Controls.Calendar" threw an exception

thank you ！

**Comment by davidgarciapallas** [comment]
Hi @prupleCode @rebeccaXam,

There are 2 errors, in the same class, Calendar.MonthNavigation, the default value for the TitleLeftArrowColorProperty and TitleRightArrowColorProperty are wrong. We need to change the "true" value for Color.Default and it works.

public static readonly BindableProperty TitleLeftArrowColorProperty =
			BindableProperty.Create(nameof(TitleLeftArrowColor), typeof(Color), typeof(Calendar), **true**,
									propertyChanged: (bindable, oldValue, newValue) => (bindable as Calendar).TitleLeftArrow.TextColor = (Color)newValue);

**Comment by rebeccaXam** [comment]
The error should be resolved in version 1.0.8. 
Please reopen this issue when the problem remains.
Please use ``TitleLeftArrowTextColor`` and ``TitleRightArrowTextColor`` as the bindable properties.

**Comment by prupleCode** [comment]
thank you very much. it works well !!
