### ISSUE TITLE
feature request: bindable property to set CalendarWeekRule

### ISSUE THREAD

**Issue by hunternope** [rebeccaXam/XamForms.Controls.Calendar#29]
XamForms.Controls.Calendar/Calendar.NumberOfWeek.cs
[](https://github.com/rebeccaXam/XamForms.Controls.Calendar/blob/862cbd9e6b222d5031a6c63c1f49fc5693ca8dba/XamForms.Controls.Calendar/Calendar.NumberOfWeek.cs#L127)

`var weekNum = ciCurr.Calendar.GetWeekOfYear(start, CalendarWeekRule.FirstFourDayWeek, StartDay);`

---

The week labels are set by default to CalendarWeekRule.FirstFourDayWeek.
I couldn't find a way to set the calenderweekrule to first full week.

**Comment by rebeccaXam** [comment]
Added Bindable property ``CalendarWeekRule`` in version 1.0.8
