### ISSUE TITLE
Dynamic specialdates dates from database is not working in Android device. 

### ISSUE THREAD

**Issue by SudharsanKrishnamoorthy** [rebeccaXam/XamForms.Controls.Calendar#3]
This Calendar is working properly with static specialdates list in Android device and emulator. On dynamic specialdates dates from database is working in emulator but Application crashing on Android device. 

[issuecalendar.txt](https://github.com/rebeccaXam/XamForms.Controls.Calendar/files/401656/issuecalendar.txt)

**Comment by rebeccaXam** [comment]
Could you send me on what kind of Exception the Calendar is crashing on the Android device?

**Comment by SudharsanKrishnamoorthy** [comment]
Error Exception has been thrown by the target of an invocation.

This exception is getting.

**Comment by SudharsanKrishnamoorthy** [comment]
I think so datetime format 12/24hrs is the issue.

**Comment by SudharsanKrishnamoorthy** [comment]
Hi, 
I got the Solution.

Datetime format is different in emulator  and Android device.  Now i changed the (mm/dd/yyyy) to (dd/mm/yyyy) now its working in android device but showing exception on Emulator.

with regards,
Sudharsan K
