### ISSUE TITLE
Windows Phone 8.1 won't run (exception at init)

### ISSUE THREAD

**Issue by hunternope** [rebeccaXam/XamForms.Controls.Calendar#33]
I get an exception at the calender.init() after xamarin.forms.init() on a fresh windows 8.1 mobile phone project.

**Comment by rebeccaXam** [comment]
Somehow the theme ``SystemControlBackgroundBaseLowBrush`` is no longer support in newer version of Windows. This should now be fixed in version 1.1.0

Please reopen this issue if you still experience problems ;)
