### ISSUE TITLE
SelectedBackgroundColor and SelectedTextColor in XAML

### ISSUE THREAD

**Issue by knasher** [rebeccaXam/XamForms.Controls.Calendar#35]
Using either option in XAML results in this runtime message:

```Cannot assign property "SelectedBackgroundColor": Property does not exists, or is not assignable, or mismatching type between value and property.```

or

```Cannot assign property "SelectedTextColor": Property does not exists, or is not assignable, or mismatching type between value and property.```

How can I set the selected background and text colour?

**Comment by rebeccaXam** [comment]
This was cause by the type being ``Color?``.
In version 1.1.0 I change the type to ``Color``  so this should be fixed in that version. Please reopen this issue if you still have problems in XAML.
