### ISSUE TITLE
Disallow to show dates outside Min Max Daterange

### ISSUE THREAD

**Issue by K232** [rebeccaXam/XamForms.Controls.Calendar#39]
Many thanks for this great plugin!

One question: Is it possible to restrict the scrolling to the Min and Max Daterange? So when I set e.g. Min to 1st January 2017 and Max to 20th March 2017, user should only be able to see January, February and March. If on January, the left back button should be disabled. Is that possible? Currently users could go back to whatever date. Of course they are greyed out, but I want to avoid user to switch outside the date range.

Many thanks!

**Comment by rebeccaXam** [comment]
In version 1.1.0 a property ``DisableDatesLimitToMaxMinRange`` is available (default is false), if you want to restrict movement then set this to true and it will disable the left/right arrow when the next/previous month are disabled fully.
