### ISSUE TITLE
Hello? How to SpecialDates click? 

### ISSUE THREAD

**Issue by moogiis** [rebeccaXam/XamForms.Controls.Calendar#4]
Hello? How to SpecialDates click?

**Comment by rebeccaXam** [comment]
Please set the property "Selectable" to "true" in your SpecialDate, then it is clickable.

Code:
```
new SpecialDate(DateTime.Now.AddDays(3)) { Selectable = true , BackgroundColor = Color.Green, TextColor = Color.Blue}
```

**Comment by moogiis** [comment]
TNX
/////////////////////

if(calendar.SelectedDate == new DateTime(2016, 8, 22))
{
     DisplayAlert("Alert", "yepp", "ok");
}

POSSIBLE??
////////////////////

**Comment by rebeccaXam** [comment]
The SpecialDates is a List<SpecialDate> you can add the special colored dates with this. The SelectedDate is the DateTime that is currently selected. You can also have the event DateClicked (or DateCommand for the ICommand of the same) that runs when a date was selected.

Something like this:
```
var calendar = new Calendar();
calendar.SpecialDates = new List<SpecialDate>{
	new SpecialDate(DateTime.Now.AddDays(2)) { BackgroundColor = Color.Red, TextColor = Color.Accent, BorderColor = Color.Maroon, BorderWidth=8 },
	new SpecialDate(DateTime.Now.AddDays(3)) { BackgroundColor = Color.Green, TextColor = Color.Blue, Selectable = true }
};
calendar.DateClicked += (sender, e) =>
{
	if (calendar.SelectedDate == new DateTime(2016, 8, 22))
	{
		DisplayAlert("Alert", "yepp", "ok");
	}
};
```

**Comment by moogiis** [comment]
sorry

```
calendar.DateClicked += (sender, e) =>
{
    if (calendar.SelectedDate == new DateTime(2016, 8, 22))
    {
        DisplayAlert("Alert", "yepp", "ok");
    }
};
```

not working. Another solution?

**Comment by moogiis** [comment]
Any help? :)

**Comment by rebeccaXam** [comment]
Try:
```
if (calendar.SelectedDate.Value.Date == new DateTime(2016, 8, 22).Date)
```

**Comment by moogiis** [comment]
YEES! its work.
Thank you so much :) 👍

**Comment by rebeccaXam** [comment]
Glad it worked out :)
