### ISSUE TITLE
Pluging has a IOS minimun compatibility in iphone?

### ISSUE THREAD

**Issue by EduardoJoseSal** [rebeccaXam/XamForms.Controls.Calendar#41]
First we want to say thanks for this great plugin.
We test the application with this pluging on a iPhone 4 with IOS 7 and the application crash when loads de calender.
The questions is if exists a mínimum version of OS in iphone for this pluging.

**Comment by rebeccaXam** [comment]
The same as for Xamarin.Forms: https://developer.xamarin.com/guides/xamarin-forms/getting-started/installation/
- iOS 6.1 or higher

So this should work, you could try removing the iOS specific assembly XamForms.Controls.Calendar.iOS.dll and remove the XamForms.Controls.iOS.Calendar.Init(); from the AppDelegate.cs and see if it still crashes. The calendar will not work correctly when the iOS part is missing (#2) but it should at least show. 
If this is the case then, there is a problem in the iOS specific code.
If you could provide me with more details on the crash, I will see what I can do to fix it.

**Comment by EduardoJoseSal** [comment]
We tried with iphone 4s ios 8 and it work fine.
So in this case we decide set this minimum version for our app like the link Xamarin.Forms provided.
Thanks.
