### ISSUE TITLE
Change TextLabel

### ISSUE THREAD

**Issue by enzosanchez2017** [rebeccaXam/XamForms.Controls.Calendar#42]
Hello, I need to change textlabel.
It is possible to change "May 2017" by May? thank you very much

**Comment by rebeccaXam** [comment]
Hello, yes you can by setting ``calendar.TitleLabelFormat = "MMMM"``
This will change the label from ``May 2017`` -> ``May``  
"MMMM" = The full name of the month.
"MMM" = The abbreviated name of the month.
For further formats see: https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.110).aspx
