### ISSUE TITLE
SelectedDay = DateTime.Today - do not change to actual month, in case I am in another monty

### ISSUE THREAD

**Issue by jsladyme** [rebeccaXam/XamForms.Controls.Calendar#44]
Hi, thank you for great calendar!
I am trying to create something like "Today" Button. Everything works fine, if actual date is loaded on screen, means I am on actual month, or on previous/next month and actual day is still visible (is part last/first  week of month).
Is there any chance to create some method, which will switch month to actual month, and Select today date?

If this functionality is already in your package and I am just only blind, let me know, how to achieve this behavior.

Thanks a lot

jslady

**Comment by rebeccaXam** [comment]
Hello, try ``calendar.StartDate = DateTime.Today;`` this will switch the month view to today's month. The ``calendar.SelectedDay = DateTime.Today;`` will only highlight today's date but will not switch to today's month.

Hoop this helps ;)

Kind regards,
Rebecca

**Comment by jsladyme** [comment]
Thanks a lot, it works!

J.
