### ISSUE TITLE
How can I get the first day displayed?

### ISSUE THREAD

**Issue by mvaz4** [rebeccaXam/XamForms.Controls.Calendar#45]
I need to get events to fill the calendar, how can I know which is the date of the first day in the calendar? Even if it is gray, as in, not from the month being displayed? At the same time, how can I get the last day being displayed?

![screenshot 2017-05-31 15 17 00](https://cloud.githubusercontent.com/assets/29099581/26636432/b37940cc-4614-11e7-86bc-4f7dd0b001f8.png)
 
Image for clarification.

Thanks in advance for the amazing tool you have developed.

**Comment by rebeccaXam** [comment]
Hello, if I understand correctly you want the dates that are marked red in your screenshot. You can get these dates by using:
```
var start = calendar.CalendarStartDate(calendar.StartDate);
var end = start.AddDays(41);
```
Hoop that helps :)

**Comment by mvaz4** [comment]
Thank you so much for responding so quickly!

It's exactly what I wanted, it seems so simple now.
