### ISSUE TITLE
SpecialDates background doesn't update when changing month

### ISSUE THREAD

**Issue by pvhd** [rebeccaXam/XamForms.Controls.Calendar#49]
Hello,

Thanks a lot for your component. When using this plug in, I found out that whenever I change the current month to next month or previous month, the special dates backgrounds in the current month still appear in the same spots in next month or previous month even though there are no special dates in next month or previous month. Could you please show me how to resolve this? 

Thanks in advance.

**Comment by rebeccaXam** [comment]
Hello,
please update the package to 1.1.1
The bug should be resolved in 1.1.1, if not please let me know.

**Comment by pvhd** [comment]
Thanks for your help. It works!
