### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by Sadoge** [rebeccaXam/XamForms.Controls.Calendar#50]
Is it possible at the moment to have multi language for the calendar?

**Comment by rebeccaXam** [comment]
By default the calendar uses the language that the Android/iOS/Windows device is set to. You can force the language by adding: 
```
Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("es-ES");
```
before the calendar is created, however this will put the whole application in Spanish.
See [CultureInfo Class](https://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo(vs.71).aspx) for more codes.

**Comment by Sadoge** [comment]
Thank you for the quick response! The language wasn't updated properly in my code. When I forced it, then it updated correctly.
