### ISSUE TITLE
Change color Arrows change moths

### ISSUE THREAD

**Issue by andreluiz1987** [rebeccaXam/XamForms.Controls.Calendar#52]
Hi.
Firstly thanks for developing this lib which is useful for my application. 

I wonder if it is possible to change the color of the arrows that change the calendar months, is currently red.

**Comment by rebeccaXam** [comment]
Yes, you can change the color with:
```
calendar.TitleLeftArrowTextColor = Color.Blue;
calendar.TitleRightArrowTextColor = Color.Blue;
```

**Comment by andreluiz1987** [comment]
Thanks!!!
