### ISSUE TITLE
Set start date

### ISSUE THREAD

**Issue by andreluiz1987** [rebeccaXam/XamForms.Controls.Calendar#53]
Hi.

I am trying to set the starting date in the calendar but I am not successful, the intention is to disable the dates below the current one.
I used StartDate and it did not work. For example, i want disable dates before 21/09/2017.
I'm running the XamForms.Controls.Calendar version "version =" 1.0.7 "

![11](https://user-images.githubusercontent.com/4265196/30701329-65f3a2fc-9ec0-11e7-9e18-a2aa706456f3.JPG)

**Comment by rebeccaXam** [comment]
Hello,

```StartDate``` is to set the date the calendar initialize with, (01/04/2018) will show at start of the calendar month 4 year 2018.

to disable all dates before 21/09/2017:
```
calendar.MinDate = new DateTime(2017,9,21);
```
to disable all dates after a certain date use, ```calendar.MaxDate```

To disable specific dates use [SpecialDates](https://github.com/rebeccaXam/XamForms.Controls.Calendar/wiki/SpecialDates).

**Comment by andreluiz1987** [comment]
it's working!

Thks.
