### ISSUE TITLE
increase cell height

### ISSUE THREAD

**Issue by rahul-tbs** [rebeccaXam/XamForms.Controls.Calendar#54]
How i can increase calendar cell height in xamarin forms..?
i am stuck in that point .
please guide me..

**Comment by rebeccaXam** [comment]
Hello,
the cells are designed to have width and height as equal as possible. 
If you really want to make the cells higher then the width use as fixed height: 
```
calendar.OnEndRenderCalendar += (sender, e) =>
{
	(calendar.Content as StackLayout).Children.Last().HeightRequest = 500;
};
```

**Comment by rahul-tbs** [comment]
Yup its working
Thanks..
