### ISSUE TITLE
Is there a way to change the month and weekday label text?

### ISSUE THREAD

**Issue by marciogonzalez85** [rebeccaXam/XamForms.Controls.Calendar#58]
I need to change the language of the calendar to pt-br (months and weekdays) but I can't find how to.
Is there a way to accomplish that?

Thanks.

**Comment by marciogonzalez85** [comment]
I just resolved that by changing thread's CurrentCulture and CurrentUICulture.

Thanks.

**Comment by Naografix** [comment]
@marciogonzalez85 Can you share me your code? I want to change my calendar language in French. Thanks for your help.

**Comment by marciogonzalez85** [comment]
Sure.

I just put these lines in the beginning of both methods FinishedLaunching from iOS AppDelegate class and OnCreate from Android MainActivity


Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("pt-BR");
Thread.CurrentThread.CurrentUICulture = new System.Globalization.CultureInfo("pt-BR");


Just replace to your culture code.


Hope it helps!!!

________________________________
De: Naografix <notifications@github.com>
Enviado: quinta-feira, 9 de novembro de 2017 10:22:58
Para: rebeccaXam/XamForms.Controls.Calendar
Cc: marciogonzalez85; Mention
Assunto: Re: [rebeccaXam/XamForms.Controls.Calendar] Is there a way to change the month and weekday label text? (#58)


@marciogonzalez85<https://github.com/marciogonzalez85> Can you share me your code? I want to change my calendar language in French. Thanks for your help.
