### ISSUE TITLE
Amount of days in a month are incorrect

### ISSUE THREAD

**Issue by Magicbjorn** [rebeccaXam/XamForms.Controls.Calendar#6]
The amount of days in a month that's displayed is always 31, no matter the month. The "DaysNotInMonth" is not correctly displayed either; for quite a lot of months, the days that are in "the next month" range from the 26th to the 2nd. For some months, days of the next month are in the current month (1st and 2nd of the next month, mostly) (see attached screenshots).

![screen shot 2016-10-04 at 09 08 04](https://cloud.githubusercontent.com/assets/14886316/19065394/90ca6c12-8a13-11e6-9c92-488e5dda101c.jpg)
![screen shot 2016-10-04 at 09 08 28](https://cloud.githubusercontent.com/assets/14886316/19065396/90d43d46-8a13-11e6-8e29-485c723cd900.jpg)
![screen shot 2016-10-04 at 09 08 51](https://cloud.githubusercontent.com/assets/14886316/19065395/90cc40aa-8a13-11e6-9813-933070927c2d.jpg)
![screen shot 2016-10-04 at 09 14 12](https://cloud.githubusercontent.com/assets/14886316/19065393/90c89c20-8a13-11e6-8029-29df99b1e89b.jpg)

**Comment by Magicbjorn** [comment]
I have found a work-around that seems to work. For iOS: if you delete the NuGet package from your .iOS project, and add the ButtonRenderer and the Assembly in a newly created Properties folder, the problem seems to be fixed.

**Comment by rebeccaXam** [comment]
This is caused by the CalendarButtons not being attached to the CalendarButtonRenderer.
Please check if you have called the init
```c#
Xamarin.Forms.Init();//platform specific init
XamForms.Controls.iOS.Calendar.Init(); // <--- this should trigger the CalendarButton to be attached to the CalendarButtonRenderer
```
Also check if the XamForms.Controls.Calendar.iOS.dll is added to your iOS runnable project, in previous version of this package (<v1.0.4) this was not the case.

If this does not help please add this to your iOS runnable Properties/AssemblyInfo.cs:
```
[assembly:Xamarin.Forms.Platform.iOS.ExportRenderer(typeof(XamForms.Controls.CalendarButton), typeof(XamForms.Controls.iOS.CalendarButtonRenderer))]

```

**Comment by schwickster** [comment]
Thanks rebeccaXam. We already applied that a few weeks ago and it worked.
