### ISSUE TITLE
New feature (Add year view)

### ISSUE THREAD

**Issue by Jakezheng** [rebeccaXam/XamForms.Controls.Calendar#7]
good plugin feature (Add year view) please

**Comment by rebeccaXam** [comment]
Sorry, I was rather busy the last 2 months. 
I will include this new feature in version 1.0.6

**Comment by rebeccaXam** [comment]
I released version 1.0.6.
You can enable `EnableTitleMonthYearView` to change the view by clicking on the Title label in the header or call `ShowYears(), ShowMonths(), ShowNormal()` to change the view.
To catch the click event use `MonthYearButtonCommand or MonthYearButtonClicked`.
