### ISSUE TITLE
How to add Events ans show them on particular day.

### ISSUE THREAD

**Issue by ashishkumawat** [rebeccaXam/XamForms.Controls.Calendar#76]
This is not issue but a request is there any way to add any events in day like Telerik or Syncfusion Calendar.

**Comment by ali-h2010** [comment]
When I used this, I handled clicking on day event to show a list of items under the calendar. This list was used to pick the available days but you can use it for anything you want like events. 

Use this Special days [https://github.com/rebeccaXam/XamForms.Controls.Calendar/wiki/SpecialDates](Special Dates) to change the appearance of those dates.

**Comment by ali-h2010** [comment]
Also , your question was already answered by the developer. So please search before you ask duplicated questions.

https://github.com/rebeccaXam/XamForms.Controls.Calendar/issues/48

**Comment by Muthutc** [comment]
Hi ali-h2010

I don't Know How do i add a event .

**Comment by zukolinux** [comment]
Adding a Event in the Calendar of Droid and IOS using Xamarin Forms.
**visit this Link**
https://github.com/DevsDNA/Samples/blob/master/XFAlarms/XFAlarms/XFAlarms.Android/XFAlarms.Android.csproj
