### ISSUE TITLE
SpecialDate not displayed

### ISSUE THREAD

**Issue by sjimpey** [rebeccaXam/XamForms.Controls.Calendar#9]
I have added a calendar to my XAML code (Xamarin.Forms on Android project), and in the constructor for the page I add several SpecialDates to the list. I have also tried to add them in the OnAppearing function with the same effect.

When the calendar is initially drawn the dates are not highlighted.

BUT, if I click to another month and back again they are shown highlighted correctly.
Also if I click on a date that I know it in the list it is highlighted correctly.

Any ideas?

Edit: Using the NuGet package v1.0.5

**Comment by rebeccaXam** [comment]
This is an common binding issue with Lists.  The problem is that the PropertyChanged event will be trigger for assigning the new list, but not for items being added or removed. Use ```RaiseSpecialDatesChanged()``` at the end of adding items to the list.

Example where nothing is highlighted at the beginning:
```c#
calendar.SpecialDates = new List<SpecialDate>() // redraw here, list is empty, so nothing will show
calendar.SpecialDates.Add(new SpecialDate(DateTime.Now.AddDays(2)) { BackgroundColor = Color.Red, TextColor = Color.Accent, BorderWidth=8 });
calendar.SpecialDates.Add(new SpecialDate(DateTime.Now.AddDays(3)) { BackgroundColor = Color.Green, TextColor = Color.Blue, Selectable = true })
// There will be no further redraw triggered by adding items to the list
// Unless you call RaiseSpecialDatesChanged
RaiseSpecialDatesChanged(); //<-- Please add this add the end of adding items to the list
```
Example where the items will show at the beginning:
```c#
var list = new List<SpecialDate>()
list.Add(new SpecialDate(DateTime.Now.AddDays(2)) { BackgroundColor = Color.Red, TextColor = Color.Accent, BorderWidth=8 });
list.Add(new SpecialDate(DateTime.Now.AddDays(3)) { BackgroundColor = Color.Green, TextColor = Color.Blue, Selectable = true })
calendar.SpecialDates = list; // redraw will be triggered here, there are 2 items in the list so, these will show
```

Hoop this helps ;)

**Comment by sjimpey** [comment]
Thanks that appears to be working now.
