### ISSUE TITLE
How refresh Calendar (Just Special Dates)

### ISSUE THREAD

**Issue by ufukhawk** [rebeccaXam/XamForms.Controls.Calendar#94]
How refresh Calendar (Just Special Dates)

**Comment by lubiepomaranczki** [comment]
Ech, please try asking questions in proper English.

If you want to refresh a calendar you can either call `ForceRedraw` or Bind ObservableCollection to `SpecialDates` property. This should do although I haven't tested it.

**Comment by VegardAaberge** [comment]
I binded it to an ObservableCollection and that is working fine. 

Just add SpecialDates="{Binding Name}" in the xaml file and create the ObservableCollection in your viewmodel.

**Comment by emir0903d** [comment]
Hi,
I'm loading SpecialDates from the database at the first construction of Calendar view model.
But I don't see notifications on calendar, not untill i click on the arrow to change the month.
So, my question is how to call ForceRedraw from VM behind CalendarPage ?
Thanks in advance.
